const KEY='harvestedResults';
const AUTH_KEY='scrappeeAuth';
const AUTO_KEY='serpAutoState';
const EMAIL_ONLY_KEY='emailOnlySerp';
const API='https://api.scrapee.uk';
const $=id=>document.getElementById(id);
fetch(chrome.runtime.getURL("manifest.json")).then(r=>r.json()).then(m=>{const v=$("version");if(v)v.textContent=`v${m.version}`;}).catch(()=>{});

async function getAuth(){try{const r=await chrome.runtime.sendMessage({type:'auth_validate'});if(r?.auth?.token){await chrome.storage.local.set({[AUTH_KEY]:r.auth});return r.auth;}}catch(_){}const v=await chrome.storage.local.get(AUTH_KEY);return v[AUTH_KEY]?.token?v[AUTH_KEY]:null;}
async function api(path,options={}){const auth=await getAuth();const headers={'Content-Type':'application/json',...(options.headers||{})};if(auth?.token)headers.Authorization=`Bearer ${auth.token}`;const r=await fetch(API+path,{...options,headers});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){data={detail:text}}if(!r.ok)throw new Error(data.detail||`API error ${r.status}`);return data;}
async function getResults(){const v=await chrome.storage.local.get(KEY);return Array.isArray(v[KEY])?v[KEY]:[];}
async function getAuto(){const v=await chrome.storage.local.get(AUTO_KEY);return v[AUTO_KEY]||null;}
async function getEmailOnly(){const v=await chrome.storage.local.get(EMAIL_ONLY_KEY);return v[EMAIL_ONLY_KEY] !== false;}
async function setEmailOnly(enabled){await chrome.storage.local.set({[EMAIL_ONLY_KEY]:!!enabled});}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderResults(results){$('results').innerHTML=results.slice(-12).reverse().map(r=>`<div class="result"><b>${esc(r.title||r.url||'')}</b><span>${esc(r.url||'')}</span><span>${esc(r.snippet||'')}</span></div>`).join('');}

async function loadCurrentScrap(){const scrap=await api('/scraps/current');if(!scrap){$('target').textContent='Current Scrap: none';return null;}$('target').textContent=`Current Scrap: ${scrap.name} — ${scrap.status}`;return scrap;}
async function renderEmailOnly(){const on=await getEmailOnly();$('emailOnly').checked=on;}

async function loadIndexedLeads(){const v=await chrome.storage.local.get('pageIndexLast');const last=v.pageIndexLast;if(!last?.job_id&&!last?.url){$('pageIndexStatus').textContent='No indexed page available.';return null;}try{const emailOnly=await getEmailOnly();const q=last.job_id?`?job_id=${encodeURIComponent(last.job_id)}&email_only=${emailOnly}`:`?url=${encodeURIComponent(last.url)}&email_only=${emailOnly}`;const data=await api(`/page-indexer/leads${q}`);await chrome.storage.local.set({pageIndexLast:{...last,job_id:data.job_id,lead_preview:data.lead_preview||[],leads:data.leads||0,charged_cents:data.charged_cents||0}});return data;}catch(e){$('pageIndexStatus').textContent=e.message||String(e);return null;}}
function renderLeadCards(leads){const rows=Array.isArray(leads)?leads:[];$('pageLeadResults').innerHTML=rows.map(l=>{const name=[l.first_name,l.last_name].filter(Boolean).join(' ')||'Unnamed lead';const role=[l.position,l.company_name].filter(Boolean).join(' — ');const contact=[l.email,l.phone].filter(Boolean).join(' · ');const location=[l.city,l.state,l.country].filter(Boolean).join(', ');return `<div class="lead-card"><div class="lead-head"><b>${esc(name)}</b><span class="lead-pill">Lead</span></div>${role?`<span>${esc(role)}</span>`:''}${contact?`<span>✉ ${esc(contact)}</span>`:''}${location?`<span>⌖ ${esc(location)}</span>`:''}${l.source_url?`<span>↗ ${esc(l.source_url)}</span>`:''}</div>`;}).join('');$('pageLeadResults').classList.toggle('hidden',!rows.length);}
async function renderPageIndex(){const r=await chrome.runtime.sendMessage({type:'page_index_get_auto'});$('pageIndexAuto').checked=!!r?.enabled;const v=await chrome.storage.local.get('pageIndexLast');const last=v.pageIndexLast;$('pageLeadCountValue').textContent=String(last?.leads||0);$('pageCost').textContent=last?.charged_cents!=null?`$${((last.charged_cents||0)/100).toFixed(2)}`:'$0.00';$('countStat').textContent=$('count').textContent||'0';if(last?.url){$('pageIndexCard').classList.remove('hidden');$('pageIndexCard').innerHTML=`<div class="index-ok"><span class="dot">✓</span>Page indexed successfully</div><div class="index-meta">${esc(last.url)}</div><div class="index-meta"><b>${last.leads||0} leads found</b> — $${((last.charged_cents||0)/100).toFixed(2)} charged</div>`;$('viewPageLeads').classList.remove('hidden');$('pageIndexStatus').textContent=`Last indexed: ${last.url}`;}else{$('pageIndexCard').classList.add('hidden');$('viewPageLeads').classList.add('hidden');}renderLeadCards(last?.lead_preview||[]);}


async function showState(){const auth=await getAuth();if(!auth?.token){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');return;}$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('account').textContent=`Logged in as ${auth.email}`;try{await loadCurrentScrap();renderResults(await getResults());await renderAuto();await renderEmailOnly();await renderPageIndex();}catch(e){$('status').textContent=e.message;}}
async function renderAuto(){const s=await getAuto();if(s?.results!=null)$('count').textContent=String(s.results);if(!s?.running){$('autoStart').classList.remove('hidden');$('autoStop').classList.add('hidden');$('autoResume').classList.add('hidden');$('startCrawl').classList.toggle('hidden',!(s?.results>0));$('status').textContent=s?.message||'Ready to collect SERP results.';return;}$('autoStart').classList.add('hidden');$('autoStop').classList.remove('hidden');$('autoResume').classList.toggle('hidden',!s.waitingChallenge);$('startCrawl').classList.add('hidden');$('status').textContent=s.message||'Automatic SERP collection running…';}

$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){$('loginStatus').textContent='Email and password are required.';return;}$('login').disabled=true;$('loginStatus').textContent='Logging in…';try{const data=await api('/auth/login',{method:'POST',headers:{'X-Scrappee-Extension':'1'},body:JSON.stringify({email,password})});await chrome.runtime.sendMessage({type:'auth_set',auth:{email:data.email,token:data.token}});$('loginStatus').textContent='';await showState();}catch(e){$('loginStatus').textContent=e.message;}finally{$('login').disabled=false;}});
$('reloadScraps').addEventListener('click',async()=>{try{await loadCurrentScrap();$('status').textContent='Current Scrap refreshed.';}catch(e){$('status').textContent=e.message;}});
$('logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});}catch(_){}await chrome.runtime.sendMessage({type:'auth_clear'});await showState();});
$('emailOnly').addEventListener('change',async()=>{const on=$('emailOnly').checked;await setEmailOnly(on);if(on){const results=await getResults();const filtered=results.filter(r=>/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i.test([r.title,r.snippet,r.raw_text].filter(Boolean).join(' ')));await chrome.storage.local.set({[KEY]:filtered});}$('status').textContent=on?'Email-only filter ON: SERPs without an email are discarded before backend submission.':'Email-only filter OFF: all qualifying SERP results may be collected.';await renderAuto();});


$('viewPageLeads').addEventListener('click',async()=>{const data=await loadIndexedLeads();if(data){renderLeadCards(data.lead_preview||[]);$('pageLeadCountValue').textContent=String(data.leads||0);$('pageCost').textContent=`$${((data.charged_cents||0)/100).toFixed(2)}`;$('pageIndexStatus').textContent=`Showing ${data.leads||0} leads from the last indexed page.`;}});
$('pageIndexAuto').addEventListener('change',async()=>{const r=await chrome.runtime.sendMessage({type:'page_index_set_auto',enabled:$('pageIndexAuto').checked});$('pageIndexStatus').textContent=r?.enabled?'Auto Indexing ON. Eligible visited pages will be indexed automatically.':'Auto Indexing OFF.';});
$('indexPage').addEventListener('click',async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error('No active page.');$('indexPage').disabled=true;$('pageIndexStatus').textContent='Indexing page…';const r=await chrome.runtime.sendMessage({type:'page_index_current',tabId:tab.id});if(!r?.ok)throw new Error(r?.error||'Page indexing failed.');const x=r.result||{};if(!x.eligible){$('pageIndexStatus').textContent='Page discarded: no lead-bearing content detected.';$('pageLeadResults').classList.add('hidden');$('pageLeadCountValue').textContent='0';}else if(x.duplicate){$('pageIndexStatus').textContent=`Page already indexed: ${x.leads||0} leads; no new charge.`;}else{$('pageIndexStatus').textContent=`Indexed: ${x.leads||0} leads — charged $${((x.charged_cents||0)/100).toFixed(2)}.`;}if(x.lead_preview||x.job_id)await chrome.storage.local.set({pageIndexLast:{...(await chrome.storage.local.get('pageIndexLast')).pageIndexLast,url:x.url||((await chrome.storage.local.get('pageIndexLast')).pageIndexLast||{}).url,job_id:x.job_id,leads:x.leads||0,charged_cents:x.charged_cents||0,lead_preview:x.lead_preview||[]}});await renderPageIndex();}catch(e){$('pageIndexStatus').textContent=e.message||String(e);}finally{$('indexPage').disabled=false;}});
$('autoStart').addEventListener('click',async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const r=await chrome.runtime.sendMessage({type:'auto_start',tabId:tab?.id});if(!r?.ok)throw new Error(r?.error||'Could not start automatic collection.');await renderAuto();await renderEmailOnly();}catch(e){$('status').textContent=e.message||String(e);}});
$('autoStop').addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:'auto_stop'});await renderAuto();});
$('autoResume').addEventListener('click',async()=>{const r=await chrome.runtime.sendMessage({type:'auto_resume'});if(!r?.ok)$('status').textContent=r?.error||'Could not resume.';else await renderAuto();});
$('startCrawl').addEventListener('click',async()=>{try{const scrap=await loadCurrentScrap();if(!scrap)throw new Error('No active Current Scrap.');await api(`/scraps/${scrap.id}/complete-submission`,{method:'POST'});const body={scrap_id:scrap.id,criteria:scrap.criteria||{},crawler:scrap.crawler||{},export_format:'csv'};const job=await api('/jobs/from-urls',{method:'POST',body:JSON.stringify(body)});$('status').textContent=`Scrapy crawl started: ${job.job_id}`;$('startCrawl').classList.add('hidden');}catch(e){$('status').textContent=e.message||String(e);}});
$('clear').addEventListener('click',async()=>{const r=await chrome.runtime.sendMessage({type:'auto_clear'});if(!r?.ok){$('status').textContent=r?.error||'Could not clear local preview.';return;}renderResults([]);await renderAuto();$('count').textContent='0';$('status').textContent='Local SERP preview cleared. Server-collected results are unchanged.';});
chrome.storage.local.get([KEY],v=>renderResults(Array.isArray(v[KEY])?v[KEY]:[]));
(async()=>{try{const r=await chrome.runtime.sendMessage({type:'auth_validate'});if(r?.auth?.token){await chrome.storage.local.set({[AUTH_KEY]:r.auth});}await showState();}catch(_){await showState();}})();
chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c[KEY])renderResults(c[KEY].newValue||[]);if(a==='local'&&c[AUTO_KEY])renderAuto();});
