const KEY='harvestedResults';
const AUTH_KEY='scrappeeAuth';
const AUTO_KEY='serpAutoState';
const API='https://api.scrapee.uk';
const $=id=>document.getElementById(id);

async function getAuth(){const v=await chrome.storage.local.get(AUTH_KEY);if(v[AUTH_KEY]?.token)return v[AUTH_KEY];try{const r=await chrome.runtime.sendMessage({type:'auth_get'});if(r?.auth?.token){await chrome.storage.local.set({[AUTH_KEY]:r.auth});return r.auth;}}catch(_){}return null;}
async function api(path,options={}){const auth=await getAuth();const headers={'Content-Type':'application/json',...(options.headers||{})};if(auth?.token)headers.Authorization=`Bearer ${auth.token}`;const r=await fetch(API+path,{...options,headers});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch(_){data={detail:text}}if(!r.ok)throw new Error(data.detail||`API error ${r.status}`);return data;}
async function getResults(){const v=await chrome.storage.local.get(KEY);return Array.isArray(v[KEY])?v[KEY]:[];}
async function getAuto(){const v=await chrome.storage.local.get(AUTO_KEY);return v[AUTO_KEY]||null;}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderResults(results){$('results').innerHTML=results.slice(-12).reverse().map(r=>`<div class="result"><b>${esc(r.title||r.url||'')}</b><span>${esc(r.url||'')}</span><span>${esc(r.snippet||'')}</span></div>`).join('');}

async function loadCurrentScrap(){const scrap=await api('/scraps/current');if(!scrap){$('target').textContent='Current Scrap: none';return null;}$('target').textContent=`Current Scrap: ${scrap.name} — ${scrap.status}`;return scrap;}
async function showState(){const auth=await getAuth();if(!auth?.token){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');return;}$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('account').textContent=`Logged in as ${auth.email}`;try{await loadCurrentScrap();renderResults(await getResults());await renderAuto();}catch(e){$('status').textContent=e.message;}}
async function renderAuto(){const s=await getAuto();if(s?.results!=null)$('count').textContent=String(s.results);if(!s?.running){$('autoStart').classList.remove('hidden');$('autoStop').classList.add('hidden');$('autoResume').classList.add('hidden');$('startCrawl').classList.toggle('hidden',!(s?.results>0));$('status').textContent=s?.message||'Ready to collect SERP results.';return;}$('autoStart').classList.add('hidden');$('autoStop').classList.remove('hidden');$('autoResume').classList.toggle('hidden',!s.waitingChallenge);$('startCrawl').classList.add('hidden');$('status').textContent=s.message||'Automatic SERP collection running…';}

$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){$('loginStatus').textContent='Email and password are required.';return;}$('login').disabled=true;$('loginStatus').textContent='Logging in…';try{const data=await api('/auth/login',{method:'POST',headers:{'X-Scrappee-Extension':'1'},body:JSON.stringify({email,password})});await chrome.storage.local.set({[AUTH_KEY]:{email:data.email,token:data.token}});await chrome.runtime.sendMessage({type:'auth_set',auth:{email:data.email,token:data.token}});$('loginStatus').textContent='';await showState();}catch(e){$('loginStatus').textContent=e.message;}finally{$('login').disabled=false;}});
$('reloadScraps').addEventListener('click',async()=>{try{await loadCurrentScrap();$('status').textContent='Current Scrap refreshed.';}catch(e){$('status').textContent=e.message;}});
$('logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});}catch(_){}await chrome.runtime.sendMessage({type:'auth_clear'});await chrome.storage.local.remove([AUTH_KEY]);await showState();});
$('autoStart').addEventListener('click',async()=>{try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const r=await chrome.runtime.sendMessage({type:'auto_start',tabId:tab?.id});if(!r?.ok)throw new Error(r?.error||'Could not start automatic collection.');await renderAuto();}catch(e){$('status').textContent=e.message||String(e);}});
$('autoStop').addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:'auto_stop'});await renderAuto();});
$('autoResume').addEventListener('click',async()=>{const r=await chrome.runtime.sendMessage({type:'auto_resume'});if(!r?.ok)$('status').textContent=r?.error||'Could not resume.';else await renderAuto();});
$('startCrawl').addEventListener('click',async()=>{try{const scrap=await loadCurrentScrap();if(!scrap)throw new Error('No active Current Scrap.');await api(`/scraps/${scrap.id}/complete-submission`,{method:'POST'});const body={scrap_id:scrap.id,criteria:scrap.criteria||{},crawler:scrap.crawler||{},export_format:'csv'};const job=await api('/jobs/from-urls',{method:'POST',body:JSON.stringify(body)});$('status').textContent=`Scrapy crawl started: ${job.job_id}`;$('startCrawl').classList.add('hidden');}catch(e){$('status').textContent=e.message||String(e);}});
$('clear').addEventListener('click',async()=>{await chrome.storage.local.remove(KEY);await chrome.action.setBadgeText({text:''});renderResults([]);$('status').textContent='Local preview cleared. Server-collected SERP results are unchanged.';});
chrome.storage.local.get([KEY],v=>renderResults(Array.isArray(v[KEY])?v[KEY]:[]));
(async()=>{try{const r=await chrome.runtime.sendMessage({type:'auth_validate'});if(r?.auth?.token){await chrome.storage.local.set({[AUTH_KEY]:r.auth});}await showState();}catch(_){await showState();}})();
chrome.storage.onChanged.addListener((c,a)=>{if(a==='local'&&c[KEY])renderResults(c[KEY].newValue||[]);if(a==='local'&&c[AUTO_KEY])renderAuto();});
