import { useEffect, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Copy, ExternalLink, Play, RefreshCw, Search, Settings2, Sparkles, UsersRound } from 'lucide-react'
import { api } from '../lib/api'
import './Dashboard.css'

type DashboardData={me:any;billing:any;current:any;scraps:any[];extension:any;deposits:any[]}
const money=(c:number|undefined)=>'$'+((c??0)/100).toFixed(2)
const label=(v:any)=>String(v??'unknown').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const counts=(s:any)=>s?.counts??{}

function StepVisual({type}:{type:number}) {
 const icons=[Search,Settings2,Play,UsersRound];const Icon=icons[type-1]
 return <div className={'sd-step-visual sd-step-visual-'+type}><div className="sd-visual-window"><div className="sd-visual-top"><i/><i/><i/></div><div className="sd-visual-body"><div className="sd-visual-icon"><Icon size={22}/></div><div className="sd-visual-lines"><b>{['Research target','Search settings','Run research','Lead results'][type-1]}</b><span/><span/></div></div>{type===3&&<div className="sd-visual-progress"><i/></div>}</div><div className="sd-step-number">0{type}</div></div>
}

function NewUserGuide(){
 const steps=[['Start a New Scrap','Choose what you want Scrappee to research.','Open New Scrap and define your research target.'],['Configure Your Search','Tell Scrappee where and what to look for.','Set keywords, location and the research options.'],['Run Your Scrap','Start the research and let Scrappee collect results.','Watch the research progress and captured URLs.'],['Review Your Leads','Work through the leads your research produced.','Open Lead Workstation to review and work your results.']]
 return <section className="sd-onboarding"><div className="sd-onboarding-head"><div><div className="sd-kicker">YOUR FIRST SCRAP</div><h2>Welcome to Scrappee</h2><p>Let’s get your first research project running. Follow these four simple steps.</p></div><NavLink className="sd-btn sd-btn-primary" to="/scrap/new"><Sparkles size={15}/> Start Your First Scrap <ArrowRight size={14}/></NavLink></div><div className="sd-step-grid">{steps.map((s,i)=><article className="sd-step-card" key={s[0]}><StepVisual type={i+1}/><div className="sd-step-copy"><h3>{s[0]}</h3><p>{s[1]}</p><span>{s[2]}</span></div></article>)}</div><div className="sd-onboarding-foot"><CheckCircle2 size={16}/><span>You can return to this guide anytime from your Dashboard.</span></div></section>
}

export default function Dashboard(){
 const [d,setD]=useState<DashboardData|null>(null);const [error,setError]=useState('');const [refreshing,setRefreshing]=useState(false);const [copied,setCopied]=useState('')
 const load=async()=>{setRefreshing(true);try{const r=await Promise.all([api<any>('/auth/me'),api<any>('/billing'),api<any>('/scraps/current'),api<any[]>('/scraps'),api<any>('/extension/status').catch(()=>({connected:false,outdated:false,latest_version:null})),api<any[]>('/billing/deposits').catch(()=>[]),api<any[]>('/billing/deposits/manual').catch(()=>[])]);setD({me:r[0],billing:r[1],current:r[2],scraps:r[3]??[],extension:r[4],deposits:[...(r[5]??[]),...(r[6]??[])].sort((a,b)=>String(b.created_at??'').localeCompare(String(a.created_at??'')))});setError('')}catch(e:any){setError(e?.message??'Could not load dashboard.')}finally{setRefreshing(false)}}
 useEffect(()=>{load()},[])
 if(!d&&!error)return <section className="sd-page"><div className="sd-loading">Loading workspace…</div></section>
 if(error&&!d)return <section className="sd-page"><div className="sd-error">{error}</div><button className="sd-btn sd-btn-secondary" onClick={load}><RefreshCw size={14}/> Try again</button></section>
 const c=counts(d?.current);const completed=(d?.scraps??[]).filter(s=>['completed','complete'].includes(String(s.status).toLowerCase())).length;const serp=c.serp_results??0;const urls=c.url_occurrences??c.urls??0;const leads=c.leads??0;const ext=d?.extension??{};const latest=ext.latest_version;const needs=!ext.connected||ext.outdated;const isNew=!d?.current&&(d?.scraps?.length??0)===0
 const copy=async(v:string)=>{try{await navigator.clipboard.writeText(v);setCopied(v);setTimeout(()=>setCopied(''),1400)}catch{}}
 return <section className="sd-page">
  <div className="sd-hero"><div className="sd-hero-copy"><div className="sd-kicker">{isNew?'GET STARTED':'OVERVIEW'}</div><h1>{isNew?'Welcome to Scrappee.':<>Welcome back{d?.me?.email?', '+String(d.me.email).split('@')[0]:''}.</>}</h1><p>{isNew?'Your workspace is ready. Start your first research project below.':'Keep your research moving from one workspace.'}</p></div><div className="sd-hero-actions"><div className="sd-balance"><small>AVAILABLE BALANCE</small><strong>{money(d?.billing?.balance_cents)}</strong><span>Credits available</span></div><button className="sd-btn sd-btn-secondary" onClick={load} disabled={refreshing}><RefreshCw size={14}/>{refreshing?'Refreshing…':'Refresh'}</button>{!isNew&&<NavLink className="sd-btn sd-btn-primary" to="/scrap/new"><Sparkles size={15}/> New Scrap</NavLink>}</div></div>
  {needs&&<div className="sd-alert"><div className="sd-alert-icon"><ExternalLink size={16}/></div><div><b>{ext.outdated?'Browser extension update required':'Browser extension not connected'}</b><p>{ext.outdated?'Update to v'+latest+' to stay compliant and capture SERP results.':'Connect the Scrappee Browser Extension to capture Google/Bing SERP results.'}</p></div><div className="sd-alert-actions"><a className="sd-btn sd-btn-primary" href="https://api.scrapee.uk/downloads/latest" target="_blank" rel="noreferrer">{latest?`Download v${latest}`:'Download latest extension'}</a><button className="sd-btn sd-btn-secondary" onClick={load}>Refresh status</button></div></div>}
  {isNew?<NewUserGuide/>:<><div className="sd-current-bar"><div><small>CURRENT WORK</small><b>{d?.current?(d.current.name??d.current.title??'Current Scrap'):'No active Scrap'}</b><span>{d?.current?'Continue where you left off.':'Start a new research project when ready.'}</span></div>{d?.current?<NavLink className="sd-btn sd-btn-light" to="/scrap/current">Continue Current Scrap <b>→</b></NavLink>:<NavLink className="sd-btn sd-btn-light" to="/scrap/new">Start New Scrap <b>→</b></NavLink>}</div>
  <div className="sd-section-title"><div className="sd-kicker">OPERATIONS</div><h2>Operational metrics</h2></div><div className="sd-metrics">{[['Active Scrap',d?.current?'Yes':'None',d?.current?.name??'No active research'],['SERP Results',serp,'Current Scrap results'],['URLs',urls,'Captured destination URLs'],['Leads',leads,'Current Scrap leads'],['Completed Scraps',completed,'Finished research projects']].map((m,i)=><article className={i===0?'sd-metric sd-metric-active':'sd-metric'} key={String(m[0])}><small>{m[0]}</small><strong>{m[1]}</strong><span>{m[2]}</span></article>)}</div>
  <section className="sd-card sd-active-card"><div className="sd-card-head"><div><div className="sd-kicker">ACTIVE WORK</div><h2>{d?.current?(d.current.name??d.current.title??'Current Scrap'):'Nothing in progress'}</h2><p>{d?.current?'Your current research is ready to continue.':'Start a New Scrap to begin collecting research.'}</p></div>{d?.current&&<span className="sd-status"><i/> {label(d.current.status)}</span>}</div>{d?.current?<div className="sd-work-row"><div><small>STAGE</small><b>{label(d.current.status)}</b></div><div><small>SERP RESULTS</small><b>{serp}</b></div><div><small>URLS</small><b>{urls}</b></div><div><small>LEADS</small><b>{leads}</b></div><NavLink className="sd-btn sd-btn-primary" to="/scrap/current">Open Current Scrap →</NavLink></div>:<div className="sd-empty">No active Scrap. Your workspace is ready for the next research project.</div>}</section>
  <section className="sd-card"><div className="sd-card-head sd-table-head"><div><h2>Recent Scraps</h2><p>The latest research projects and their persisted results.</p></div><NavLink className="sd-btn sd-btn-secondary" to="/history">Open Scrap Library</NavLink></div>{d?.scraps?.length?<div className="sd-table-wrap"><table className="sd-table"><thead><tr><th>SCRAP</th><th>STATUS</th><th>RESULTS</th><th>LEADS</th><th>CREATED</th><th></th></tr></thead><tbody>{d.scraps.slice(0,20).map(s=>{const x=counts(s);return <tr key={s.id}><td><b>{s.name??s.title??s.id}</b></td><td><span className="sd-badge">{label(s.status)}</span></td><td>{x.serp_results??0}</td><td>{x.leads??0}</td><td>{s.created_at?new Date(s.created_at).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}</td><td><NavLink className="sd-link" to="/history">Details</NavLink></td></tr>})}</tbody></table></div>:<div className="sd-empty">No Scraps yet.</div>}</section>
  <section className="sd-card"><div className="sd-card-head sd-table-head"><div><h2>Deposit History</h2><p>Wallet funding activity across configured channels.</p></div><NavLink className="sd-btn sd-btn-secondary" to="/deposit">Open Deposit</NavLink></div>{d?.deposits?.length?<div className="sd-table-wrap"><table className="sd-table"><thead><tr><th>METHOD</th><th>AMOUNT</th><th>STATUS</th><th>REFERENCE</th><th>DATE</th></tr></thead><tbody>{d.deposits.slice(0,50).map((p,i)=>{const amount=p.requested_cents??p.amount_cents??0;const ref=String(p.invoice_id??p.reference??'');const method=p.asset?p.asset+' / BTCPay':p.method==='usdt_manual'?'USDT / Manual':'Bank Transfer';return <tr key={p.id??i}><td><b>{method}</b></td><td>{money(amount)}</td><td><span className="sd-badge">{label(p.status)}</span></td><td><div className="sd-ref">{ref||'—'}{ref&&<button onClick={()=>copy(ref)}>{copied===ref?<CheckCircle2 size={13}/>:<Copy size={13}/>}</button>}</div></td><td>{p.created_at?new Date(p.created_at).toLocaleString():'—'}</td></tr>})}</tbody></table></div>:<div className="sd-empty sd-empty-small">No deposits yet.</div>}</section></>}
 </section>
}
